/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useRef, useEffect } from 'react';
import { useGLTF } from '@react-three/drei';
import { useFrame, useThree } from '@react-three/fiber';
import { a } from '@react-spring/three';

import glowstickScene from '/assets/3d/glowstick.gltf?url';  

const Glowstick = (props) => {  // 컴포넌트 이름을 대문자로 수정
  const glowstickRef = useRef();  

  const { nodes, materials } = useGLTF(glowstickScene);  
  console.log(nodes, materials);

  return (
    <a.group ref={glowstickRef} {...props}>  
      <mesh
        geometry={nodes.Torus004.geometry}
        material={materials.매테리얼}
        position={[2.851, -2.399, -5.733]}
        rotation={[-0.808, -0.28, -0.103]}
      />
      <mesh
        geometry={nodes.Stick.geometry}
        material={materials['매테리얼.001']}
        position={[0.253, 3.115, -1.444]}
        rotation={[-0.808, -0.28, -0.103]}
      />
    </a.group>
  )
}

export default Glowstick;  // 대문자 G로 내보내기
