/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useEffect, forwardRef } from 'react';
import { useGLTF } from '@react-three/drei';
import { useFrame, useThree } from '@react-three/fiber';
import { a } from '@react-spring/three';


import SheepScene from '/assets/3d/Sheep.gltf?url';  


const Sheep = forwardRef((props, ref) => {  
  const { nodes, materials } = useGLTF(SheepScene);  
  console.log(nodes, materials);


  return (
    <a.group ref={ref} {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SheepFace.geometry}
        material={materials.Sheep}
      />
      <mesh castShadow receiveShadow geometry={nodes.Sheep.geometry} material={materials.Sheep} />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['SheepEar'].geometry}
        material={materials.SheepEar}
        position={[0.899, 2.131, 0.25]}
        rotation={[-1.919, -0.301, -1.64]}
        scale={0.27}
      />
    </a.group>
  )
});

Sheep.displayName = 'Sheep';

export default Sheep;

//useGLTF.preload('/Sheep.gltf')