/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useRef, useEffect } from 'react';
import { useGLTF } from '@react-three/drei';
import { useFrame, useThree } from '@react-three/fiber';
import { a } from '@react-spring/three';


import SheepScene from '/assets/3d/Sheep.gltf?url';  


const Sheep = (props) => {  // 컴포넌트 이름을 대문자로 수정
  const SheepRef = useRef();  

  const { nodes, materials } = useGLTF(SheepScene);  
  console.log(nodes, materials);


  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SheepFace.geometry}
        material={materials.Sheep}
      />
      <mesh castShadow receiveShadow geometry={nodes.Sheep.geometry} material={materials.Sheep} />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['SheepEar'].geometry}
        material={materials.SheepEar}
        position={[0.899, 2.131, 0.25]}
        rotation={[-1.919, -0.301, -1.64]}
        scale={0.27}
      />
    </group>
  )
}

export default Sheep;

//useGLTF.preload('/Sheep.gltf')