/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useEffect, forwardRef, useState } from 'react';
import { useGLTF } from '@react-three/drei';
import { useFrame, useThree } from '@react-three/fiber';
import { a } from '@react-spring/three';
import * as THREE from 'three';

import SightScene from '/assets/3d/Sight.gltf?url';  

const Sight = forwardRef(({ isAnimating = false, ...props }, ref) => {  
  const { nodes, materials } = useGLTF(SightScene);
  
  // 물고기 메쉬에 대한 레퍼런스 생성
  const fishRef = useRef();
  const mainFishRef = useRef();
  const sightMeshRef = useRef(); // Sight 메쉬에 대한 참조 추가
  
  // 물고기 애니메이션을 위한 상태
  const [fishAngle, setFishAngle] = useState(0);
  const [mainFishAngle, setMainFishAngle] = useState(Math.PI);
  
  // 물고기 초기 위치와 마지막 위치 저장
  const initialFishPos = useRef({ x: 0.482, y: 0.402, z: -1.193 });
  const initialMainFishPos = useRef({ x: -0.527, y: 0.223, z: -1.606 });
  
  // 마지막으로 저장된 각도 및 위치 (팝업 닫힐 때 저장됨)
  const lastFishAngle = useRef(0);
  const lastMainFishAngle = useRef(Math.PI);
  
  // 최초 실행 여부 추적
  const isFirstRun = useRef(true);
  
  // 애니메이션 시작 flag
  const [animationStarted, setAnimationStarted] = useState(false);
  
  // Sight 메쉬의 중심 위치 참조 (기준점)
  const sightCenterRef = useRef({ x: 0, y: 0.485, z: 0.063 });
  
  // Sight 메쉬 위치가 업데이트되면 중심점도 업데이트
  useEffect(() => {
    if (sightMeshRef.current) {
      sightCenterRef.current = {
        x: sightMeshRef.current.position.x,
        y: sightMeshRef.current.position.y,
        z: sightMeshRef.current.position.z
      };
      console.log('Sight center updated:', sightCenterRef.current);
    }
  }, []);
  
  // isAnimating 값이 변경될 때 애니메이션 시작/중지 처리
  useEffect(() => {
    if (isAnimating) {
      // 애니메이션 시작할 때
      setAnimationStarted(false);
      
      // 최초 실행이 아닌 경우 (팝업이 다시 열렸을 때), 마지막 저장된 각도로 설정
      if (!isFirstRun.current) {
        console.log('재시작: 마지막 저장된 각도로 설정', lastFishAngle.current, lastMainFishAngle.current);
        setFishAngle(lastFishAngle.current);
        setMainFishAngle(lastMainFishAngle.current);
      } else {
        // 최초 실행 시에는 초기 위치 기반 각도 계산
        const fishDx = initialFishPos.current.x - sightCenterRef.current.x;
        const fishDz = initialFishPos.current.z - sightCenterRef.current.z;
        const mainFishDx = initialMainFishPos.current.x - sightCenterRef.current.x;
        const mainFishDz = initialMainFishPos.current.z - sightCenterRef.current.z;
        
        // 초기 각도 설정
        setFishAngle(Math.atan2(fishDz, fishDx));
        setMainFishAngle(Math.atan2(mainFishDz, mainFishDx));
        
        // 최초 실행 플래그 업데이트
        isFirstRun.current = false;
      }
    } else {
      // 애니메이션 중지할 때 (팝업 닫힐 때)
      if (animationStarted) {
        // 현재 내부 각도 상태에서 마지막 위치 저장
        lastFishAngle.current = currentAngles.current.fish;
        lastMainFishAngle.current = currentAngles.current.mainFish;
        console.log('애니메이션 중지: 현재 각도 저장', lastFishAngle.current, lastMainFishAngle.current);
      }
    }
  }, [isAnimating]); // 의존성 최소화
  
  // 애니메이션 프레임마다 물고기 위치 업데이트
  // 내부 각도 상태 변수 - 직접 수정하여 React 렌더링 회피
  const currentAngles = useRef({ fish: 0, mainFish: Math.PI });
  
  useFrame((state, delta) => {
    // isAnimating이 true일 때만 물고기가 움직임
    if (isAnimating && fishRef.current && mainFishRef.current) {
      // 애니메이션이 시작될 때만 React 상태에서 내부 각도 변수 업데이트
      if (!animationStarted) {
        currentAngles.current.fish = fishAngle;
        currentAngles.current.mainFish = mainFishAngle;
        setAnimationStarted(true);
        console.log('애니메이션 시작: 각도 초기화', currentAngles.current);
      }
      
      // 회전 중심점 (Sight 모델 중심)
      const centerX = sightCenterRef.current.x;
      const centerZ = sightCenterRef.current.z;
      
      // 회전 속도 계산 - React 상태 업데이트 없이 직접 각도 수정
      const rotationSpeed = delta * 0.6;
      currentAngles.current.fish += rotationSpeed;
      currentAngles.current.mainFish += rotationSpeed;
      
      // 회전 반경 계산 - 더 좁은 반경으로 조정 (기존 반경의 70%로 줄임)
      const fishDx = initialFishPos.current.x - centerX;
      const fishDz = initialFishPos.current.z - centerZ;
      const originalFishRadius = Math.sqrt(fishDx * fishDx + fishDz * fishDz);
      const fishRadius = originalFishRadius * 0.7; // 반경을 70%로 줄임
      
      const mainFishDx = initialMainFishPos.current.x - centerX;
      const mainFishDz = initialMainFishPos.current.z - centerZ;
      const originalMainFishRadius = Math.sqrt(mainFishDx * mainFishDx + mainFishDz * mainFishDz);
      const mainFishRadius = originalMainFishRadius * 0.7; // 반경을 70%로 줄임
      
      // Fish 위치 계산 및 업데이트
      const fishAngleNow = currentAngles.current.fish;
      const fishOffsetX = fishRadius * Math.cos(fishAngleNow);
      const fishOffsetZ = fishRadius * Math.sin(fishAngleNow);
      fishRef.current.position.x = centerX + fishOffsetX;
      fishRef.current.position.z = centerZ + fishOffsetZ;
      fishRef.current.rotation.y = Math.atan2(fishOffsetX, fishOffsetZ) - Math.PI / 2;
      
      // MainFish 위치 계산 및 업데이트
      const mainFishAngleNow = currentAngles.current.mainFish;
      const mainFishOffsetX = mainFishRadius * Math.cos(mainFishAngleNow);
      const mainFishOffsetZ = mainFishRadius * Math.sin(mainFishAngleNow);
      mainFishRef.current.position.x = centerX + mainFishOffsetX;
      mainFishRef.current.position.z = centerZ + mainFishOffsetZ;
      mainFishRef.current.rotation.y = Math.atan2(mainFishOffsetX, mainFishOffsetZ) - Math.PI / 2;
      
      // Y축 방향으로 약간의 파도 운동 추가
      const time = state.clock.getElapsedTime();
      fishRef.current.position.y = initialFishPos.current.y + Math.sin(time * 2) * 0.05;
      mainFishRef.current.position.y = initialMainFishPos.current.y + Math.sin(time * 1.5) * 0.07;
      
      // 주기적으로 React 상태 업데이트 (애니메이션 중지 시 마지막 위치 저장을 위해)
      if (Math.floor(time * 10) % 10 === 0) {
        setFishAngle(currentAngles.current.fish);
        setMainFishAngle(currentAngles.current.mainFish);
      }
    }
  });

  return (
    <a.group ref={ref} {...props}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Flower.geometry}
        material={materials.Flower}
        position={[0.003, 1.211, 0.063]}
        scale={0.531}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle002.geometry}
        material={materials.Circle}
        position={[0.004, 1.102, -0.303]}
        rotation={[-0.268, -0.035, -0.006]}
        scale={0.074}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle001.geometry}
        material={materials.Circle}
        position={[0.365, 1.1, -0.051]}
        rotation={[-0.08, -0.013, -0.242]}
        scale={0.074}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle003.geometry}
        material={materials.Circle}
        position={[-0.217, 1.102, 0.367]}
        rotation={[0.236, -0.061, 0.169]}
        scale={0.074}
      />
      <mesh
        ref={sightMeshRef}
        castShadow
        receiveShadow
        geometry={nodes.Sight.geometry}
        material={materials.Sight}
        position={[0, 0.485, 0.063]}
      />

      <mesh
        ref={mainFishRef}
        castShadow
        receiveShadow
        geometry={nodes.MainFish.geometry}
        material={materials.MainFish}
        position={[-0.527, 0.223, -1.606]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[0.037, 0.127, 0.095]}
      />
      
      <mesh
        ref={fishRef}
        castShadow
        receiveShadow
        geometry={nodes.Fish.geometry}
        material={materials.Fish}
        position={[0.482, 0.402, -1.193]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[0.037, 0.127, 0.095]}
      />
      {/* <mesh
        castShadow
        receiveShadow
        geometry={nodes.Line.geometry}
        material={materials.Line}
        scale={0.993}
      /> */}
    </a.group>
  )
});

Sight.displayName = 'Sight';

export default Sight;
useGLTF.preload('/Sight.gltf')
