/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useEffect, forwardRef } from 'react';
import { useGLTF } from '@react-three/drei';
import { useFrame, useThree } from '@react-three/fiber';
import { a } from '@react-spring/three';

import TimeCapsuleScene from '/assets/3d/TimeCapsule.gltf?url';  


const TimeCapsule = forwardRef((props, ref) => {  
  const { nodes, materials } = useGLTF(TimeCapsuleScene);  
  console.log(nodes, materials);

  return (
     <a.group ref={ref} {...props}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.TimeCapsuleCover.geometry}
        material={materials.Cover}
        scale={0.17}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.TimeCapsuleBall.geometry}
        material={materials.Ball}
        position={[0, 0.115, 0]}
        scale={[-0.13, -0.133, -0.13]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.TimeCapsulePaper.geometry}
        material={materials.WhitePaper}
        position={[0, 0.25, 0]}
        scale={[0.163, 0.128, 0.163]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.TimeCapsuleBall001.geometry}
        material={materials.Ball}
        position={[0, 1.346, 0]}
        scale={[-0.13, -0.133, -0.13]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.TimeCapsuleCover001.geometry}
        material={materials.Cover}
        position={[0, 1.455, 0]}
        rotation={[0, 0, 3.142]}
        scale={0.17}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.TimeCapsulePaper001.geometry}
        material={materials.GreenPaper}
        position={[0, 0.245, 0]}
        scale={0.126}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.TimeCapsuleGlass.geometry}
        material={materials['TimeGlass']}
        scale={[0.411, 0.603, 0.411]}
      />
    </a.group>
  )
});

TimeCapsule.displayName = 'TimeCapsule';

export default TimeCapsule;
useGLTF.preload('/TimeCapsule.gltf')