/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useRef, useEffect } from 'react';
import { useGLTF } from '@react-three/drei';
import { useFrame, useThree } from '@react-three/fiber';
import { a } from '@react-spring/three';
import * as THREE from 'three'; 

import TripScene from '/assets/3d/Trip.gltf?url';  


const Trip = (props) => {  
  const TripRef = useRef();  

  const { nodes, materials } = useGLTF(TripScene);  
  console.log(nodes, materials);

  return (
    <a.group ref={TripRef} {...props}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.CubeGlass.geometry}
        material={materials['CubeGlass']}
        position={[0.186, 0.974, -0.085]}
        scale={[0.14, 1, 2.025]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.CubeSkyGlass.geometry}
        material={materials['CubeGlass']}
        position={[0.186, 0.974, -0.108]}
        scale={[0.101, 0.77, 1.867]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Handle.geometry}
        material={materials.Handle}
        position={[0.222, 0, 1.998]}
        scale={[0.245, 0.136, 0.493]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.AIr.geometry}
        material={materials.MapWhite}
        position={[0.195, 0.721, 0.922]}
        rotation={[0, 0, -1.571]}
        scale={[0.112, 0.423, 0.423]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['Map'].geometry}
        material={materials.MapWhite}
        position={[0.204, 0.443, -0.323]}
        rotation={[0.126, -0.003, -1.57]}
        scale={[0.078, 0.089, 0.096]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.CubeSky.geometry}
        material={materials['매테리얼.004']}
        position={[0.146, 0.974, -0.161]}
        scale={[0.036, 0.728, 1.762]}
        
        
        
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cloud.geometry}
        material={materials.MapWhite}
        position={[0.21, 1.211, 1.245]}
        rotation={[-0.191, 0, -1.571]}
        scale={[0.201, 0.256, 0.201]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.TripStar.geometry}
        material={nodes.TripStar.material}
        position={[0.205, 0.428, -1.386]}
        rotation={[-0.282, -0.006, -1.593]}
        scale={[0.023, 0.047, 0.023]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.텍스트.geometry}
        material={nodes.텍스트.material}
        position={[0.319, 1.432, -0.114]}
        rotation={[1.571, 0, -Math.PI / 2]}
        scale={0.282}
      />
    </a.group>
  )
}

export default Trip;
// useGLTF.preload('/Trip.gltf')
